install.packages("shiny")
install.packages("shinyscreenshot")
install.packages("shinydashboard")
install.packages("shinythemes")
install.packages("partykit")
install.packages("ggplot2")
install.packages("ggparty")
install.packages("quantmod")
install.packages("dplyr")
install.packages("reshape2")
install.packages("reshape")
install.packages("DT")
install.packages("tidyverse")
install.packages("lubridate")
install.packages("forecast")
install.packages("DescTools")
install.packages("sandwich")

